//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProvider.ScadaWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/WebServiceGIS.asmx", ConfigurationName="ScadaWebService.WebServiceGISSoap")]
    public interface WebServiceGISSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_PM1_GT11", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCongSuat_PM1_GT11(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_PM1_GT11", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCongSuat_PM1_GT11Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_PM1_GT12", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCongSuat_PM1_GT12(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_PM1_GT12", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCongSuat_PM1_GT12Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_PM1_GT13", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCongSuat_PM1_GT13(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_PM1_GT13", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCongSuat_PM1_GT13Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_PM1_ST14", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCongSuat_PM1_ST14(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_PM1_ST14", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCongSuat_PM1_ST14Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_PM4_GT41", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCongSuat_PM4_GT41(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_PM4_GT41", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCongSuat_PM4_GT41Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_PM4_GT42", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCongSuat_PM4_GT42(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_PM4_GT42", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCongSuat_PM4_GT42Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_PM4_ST43", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCongSuat_PM4_ST43(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_PM4_ST43", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCongSuat_PM4_ST43Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_PM21_GT21", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCongSuat_PM21_GT21(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_PM21_GT21", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCongSuat_PM21_GT21Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_PM21_GT22", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCongSuat_PM21_GT22(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_PM21_GT22", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCongSuat_PM21_GT22Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_PM21_ST23", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCongSuat_PM21_ST23(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_PM21_ST23", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCongSuat_PM21_ST23Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_PM21MR_GT24", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCongSuat_PM21MR_GT24(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_PM21MR_GT24", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCongSuat_PM21MR_GT24Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_PM21MR_GT25", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCongSuat_PM21MR_GT25(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_PM21MR_GT25", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCongSuat_PM21MR_GT25Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_PM21MR_ST26", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCongSuat_PM21MR_ST26(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_PM21MR_ST26", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCongSuat_PM21MR_ST26Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_VT2_S1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCongSuat_VT2_S1(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_VT2_S1", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCongSuat_VT2_S1Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_VT2_S2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCongSuat_VT2_S2(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_VT2_S2", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCongSuat_VT2_S2Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_MD1_S1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCongSuat_MD1_S1(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_MD1_S1", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCongSuat_MD1_S1Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_MD1_S2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCongSuat_MD1_S2(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_MD1_S2", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCongSuat_MD1_S2Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_BTS_H1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCongSuat_BTS_H1(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_BTS_H1", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCongSuat_BTS_H1Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_BTS_H2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCongSuat_BTS_H2(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_BTS_H2", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCongSuat_BTS_H2Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_BK_H1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCongSuat_BK_H1(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_BK_H1", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCongSuat_BK_H1Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_BK_H2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCongSuat_BK_H2(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_BK_H2", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCongSuat_BK_H2Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_SP3_H1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCongSuat_SP3_H1(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_SP3_H1", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCongSuat_SP3_H1Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_SP3_H2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCongSuat_SP3_H2(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_SP3_H2", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCongSuat_SP3_H2Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCeMSVT2_Dust_S1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCeMSVT2_Dust_S1(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCeMSVT2_Dust_S1", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCeMSVT2_Dust_S1Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCeMSVT2_Dust_S2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCeMSVT2_Dust_S2(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCeMSVT2_Dust_S2", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCeMSVT2_Dust_S2Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCeMSVT2_NO2_S1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCeMSVT2_NO2_S1(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCeMSVT2_NO2_S1", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCeMSVT2_NO2_S1Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCeMSVT2_NO2_S2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCeMSVT2_NO2_S2(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCeMSVT2_NO2_S2", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCeMSVT2_NO2_S2Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCeMSVT2_SO2_S1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCeMSVT2_SO2_S1(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCeMSVT2_SO2_S1", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCeMSVT2_SO2_S1Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCeMSVT2_SO2_S2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCeMSVT2_SO2_S2(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCeMSVT2_SO2_S2", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCeMSVT2_SO2_S2Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCeMSVT2_CO2_S1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCeMSVT2_CO2_S1(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCeMSVT2_CO2_S1", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCeMSVT2_CO2_S1Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCeMSVT2_CO2_S2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCeMSVT2_CO2_S2(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCeMSVT2_CO2_S2", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCeMSVT2_CO2_S2Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCeMSVT2_O2_S1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCeMSVT2_O2_S1(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCeMSVT2_O2_S1", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCeMSVT2_O2_S1Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCeMSVT2_O2_S2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCeMSVT2_O2_S2(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCeMSVT2_O2_S2", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCeMSVT2_O2_S2Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCeMSVT2_CO_S1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCeMSVT2_CO_S1(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCeMSVT2_CO_S1", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCeMSVT2_CO_S1Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCeMSVT2_CO_S2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCeMSVT2_CO_S2(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCeMSVT2_CO_S2", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCeMSVT2_CO_S2Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCeMSVT2_Temp_S1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCeMSVT2_Temp_S1(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCeMSVT2_Temp_S1", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCeMSVT2_Temp_S1Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCeMSVT2_Temp_S2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCeMSVT2_Temp_S2(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCeMSVT2_Temp_S2", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCeMSVT2_Temp_S2Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_PM3_GT31", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCongSuat_PM3_GT31(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_PM3_GT31", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCongSuat_PM3_GT31Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_PM3_GT32", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCongSuat_PM3_GT32(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_PM3_GT32", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCongSuat_PM3_GT32Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_PM3_ST33", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCongSuat_PM3_ST33(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_PM3_ST33", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCongSuat_PM3_ST33Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_PM22_TOTAL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCongSuat_PM22_TOTAL(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_PM22_TOTAL", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCongSuat_PM22_TOTALAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_BR_GT1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCongSuat_BR_GT1(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_BR_GT1", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCongSuat_BR_GT1Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_BR_GT2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCongSuat_BR_GT2(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_BR_GT2", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCongSuat_BR_GT2Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_BR_GT3", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCongSuat_BR_GT3(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_BR_GT3", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCongSuat_BR_GT3Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_BR_GT4", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCongSuat_BR_GT4(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_BR_GT4", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCongSuat_BR_GT4Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_BR_GT5", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCongSuat_BR_GT5(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_BR_GT5", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCongSuat_BR_GT5Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_BR_GT6", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCongSuat_BR_GT6(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_BR_GT6", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCongSuat_BR_GT6Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_BR_GT7", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCongSuat_BR_GT7(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_BR_GT7", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCongSuat_BR_GT7Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_BR_GT8", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCongSuat_BR_GT8(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_BR_GT8", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCongSuat_BR_GT8Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_BR_ST9", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCongSuat_BR_ST9(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_BR_ST9", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCongSuat_BR_ST9Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_BR_ST10", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCongSuat_BR_ST10(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_BR_ST10", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCongSuat_BR_ST10Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getGAS_LH", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getGAS_LH(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getGAS_LH", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getGAS_LHAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getGAS_DC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getGAS_DC(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getGAS_DC", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getGAS_DCAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getGAS_DC_FLOW", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getGAS_DC_FLOW(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getGAS_DC_FLOW", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getGAS_DC_FLOWAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_TB1_S1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCongSuat_TB1_S1(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_TB1_S1", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCongSuat_TB1_S1Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_TB1_S2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCongSuat_TB1_S2(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_TB1_S2", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCongSuat_TB1_S2Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_TB1_NGAY", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getCongSuat_TB1_NGAY(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_TB1_NGAY", ReplyAction="*")]
        System.Threading.Tasks.Task<string> getCongSuat_TB1_NGAYAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_VT4_S1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCongSuat_VT4_S1(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_VT4_S1", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCongSuat_VT4_S1Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_VT4_S2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCongSuat_VT4_S2(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_VT4_S2", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCongSuat_VT4_S2Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_VT4_NGAY", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getCongSuat_VT4_NGAY(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_VT4_NGAY", ReplyAction="*")]
        System.Threading.Tasks.Task<string> getCongSuat_VT4_NGAYAsync(string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceGISSoapChannel : DataProvider.ScadaWebService.WebServiceGISSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceGISSoapClient : System.ServiceModel.ClientBase<DataProvider.ScadaWebService.WebServiceGISSoap>, DataProvider.ScadaWebService.WebServiceGISSoap {
        
        public WebServiceGISSoapClient() {
        }
        
        public WebServiceGISSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceGISSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceGISSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceGISSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double getCongSuat_PM1_GT11(string id) {
            return base.Channel.getCongSuat_PM1_GT11(id);
        }
        
        public System.Threading.Tasks.Task<double> getCongSuat_PM1_GT11Async(string id) {
            return base.Channel.getCongSuat_PM1_GT11Async(id);
        }
        
        public double getCongSuat_PM1_GT12(string id) {
            return base.Channel.getCongSuat_PM1_GT12(id);
        }
        
        public System.Threading.Tasks.Task<double> getCongSuat_PM1_GT12Async(string id) {
            return base.Channel.getCongSuat_PM1_GT12Async(id);
        }
        
        public double getCongSuat_PM1_GT13(string id) {
            return base.Channel.getCongSuat_PM1_GT13(id);
        }
        
        public System.Threading.Tasks.Task<double> getCongSuat_PM1_GT13Async(string id) {
            return base.Channel.getCongSuat_PM1_GT13Async(id);
        }
        
        public double getCongSuat_PM1_ST14(string id) {
            return base.Channel.getCongSuat_PM1_ST14(id);
        }
        
        public System.Threading.Tasks.Task<double> getCongSuat_PM1_ST14Async(string id) {
            return base.Channel.getCongSuat_PM1_ST14Async(id);
        }
        
        public double getCongSuat_PM4_GT41(string id) {
            return base.Channel.getCongSuat_PM4_GT41(id);
        }
        
        public System.Threading.Tasks.Task<double> getCongSuat_PM4_GT41Async(string id) {
            return base.Channel.getCongSuat_PM4_GT41Async(id);
        }
        
        public double getCongSuat_PM4_GT42(string id) {
            return base.Channel.getCongSuat_PM4_GT42(id);
        }
        
        public System.Threading.Tasks.Task<double> getCongSuat_PM4_GT42Async(string id) {
            return base.Channel.getCongSuat_PM4_GT42Async(id);
        }
        
        public double getCongSuat_PM4_ST43(string id) {
            return base.Channel.getCongSuat_PM4_ST43(id);
        }
        
        public System.Threading.Tasks.Task<double> getCongSuat_PM4_ST43Async(string id) {
            return base.Channel.getCongSuat_PM4_ST43Async(id);
        }
        
        public double getCongSuat_PM21_GT21(string id) {
            return base.Channel.getCongSuat_PM21_GT21(id);
        }
        
        public System.Threading.Tasks.Task<double> getCongSuat_PM21_GT21Async(string id) {
            return base.Channel.getCongSuat_PM21_GT21Async(id);
        }
        
        public double getCongSuat_PM21_GT22(string id) {
            return base.Channel.getCongSuat_PM21_GT22(id);
        }
        
        public System.Threading.Tasks.Task<double> getCongSuat_PM21_GT22Async(string id) {
            return base.Channel.getCongSuat_PM21_GT22Async(id);
        }
        
        public double getCongSuat_PM21_ST23(string id) {
            return base.Channel.getCongSuat_PM21_ST23(id);
        }
        
        public System.Threading.Tasks.Task<double> getCongSuat_PM21_ST23Async(string id) {
            return base.Channel.getCongSuat_PM21_ST23Async(id);
        }
        
        public double getCongSuat_PM21MR_GT24(string id) {
            return base.Channel.getCongSuat_PM21MR_GT24(id);
        }
        
        public System.Threading.Tasks.Task<double> getCongSuat_PM21MR_GT24Async(string id) {
            return base.Channel.getCongSuat_PM21MR_GT24Async(id);
        }
        
        public double getCongSuat_PM21MR_GT25(string id) {
            return base.Channel.getCongSuat_PM21MR_GT25(id);
        }
        
        public System.Threading.Tasks.Task<double> getCongSuat_PM21MR_GT25Async(string id) {
            return base.Channel.getCongSuat_PM21MR_GT25Async(id);
        }
        
        public double getCongSuat_PM21MR_ST26(string id) {
            return base.Channel.getCongSuat_PM21MR_ST26(id);
        }
        
        public System.Threading.Tasks.Task<double> getCongSuat_PM21MR_ST26Async(string id) {
            return base.Channel.getCongSuat_PM21MR_ST26Async(id);
        }
        
        public double getCongSuat_VT2_S1(string id) {
            return base.Channel.getCongSuat_VT2_S1(id);
        }
        
        public System.Threading.Tasks.Task<double> getCongSuat_VT2_S1Async(string id) {
            return base.Channel.getCongSuat_VT2_S1Async(id);
        }
        
        public double getCongSuat_VT2_S2(string id) {
            return base.Channel.getCongSuat_VT2_S2(id);
        }
        
        public System.Threading.Tasks.Task<double> getCongSuat_VT2_S2Async(string id) {
            return base.Channel.getCongSuat_VT2_S2Async(id);
        }
        
        public double getCongSuat_MD1_S1(string id) {
            return base.Channel.getCongSuat_MD1_S1(id);
        }
        
        public System.Threading.Tasks.Task<double> getCongSuat_MD1_S1Async(string id) {
            return base.Channel.getCongSuat_MD1_S1Async(id);
        }
        
        public double getCongSuat_MD1_S2(string id) {
            return base.Channel.getCongSuat_MD1_S2(id);
        }
        
        public System.Threading.Tasks.Task<double> getCongSuat_MD1_S2Async(string id) {
            return base.Channel.getCongSuat_MD1_S2Async(id);
        }
        
        public double getCongSuat_BTS_H1(string id) {
            return base.Channel.getCongSuat_BTS_H1(id);
        }
        
        public System.Threading.Tasks.Task<double> getCongSuat_BTS_H1Async(string id) {
            return base.Channel.getCongSuat_BTS_H1Async(id);
        }
        
        public double getCongSuat_BTS_H2(string id) {
            return base.Channel.getCongSuat_BTS_H2(id);
        }
        
        public System.Threading.Tasks.Task<double> getCongSuat_BTS_H2Async(string id) {
            return base.Channel.getCongSuat_BTS_H2Async(id);
        }
        
        public double getCongSuat_BK_H1(string id) {
            return base.Channel.getCongSuat_BK_H1(id);
        }
        
        public System.Threading.Tasks.Task<double> getCongSuat_BK_H1Async(string id) {
            return base.Channel.getCongSuat_BK_H1Async(id);
        }
        
        public double getCongSuat_BK_H2(string id) {
            return base.Channel.getCongSuat_BK_H2(id);
        }
        
        public System.Threading.Tasks.Task<double> getCongSuat_BK_H2Async(string id) {
            return base.Channel.getCongSuat_BK_H2Async(id);
        }
        
        public double getCongSuat_SP3_H1(string id) {
            return base.Channel.getCongSuat_SP3_H1(id);
        }
        
        public System.Threading.Tasks.Task<double> getCongSuat_SP3_H1Async(string id) {
            return base.Channel.getCongSuat_SP3_H1Async(id);
        }
        
        public double getCongSuat_SP3_H2(string id) {
            return base.Channel.getCongSuat_SP3_H2(id);
        }
        
        public System.Threading.Tasks.Task<double> getCongSuat_SP3_H2Async(string id) {
            return base.Channel.getCongSuat_SP3_H2Async(id);
        }
        
        public double getCeMSVT2_Dust_S1(string id) {
            return base.Channel.getCeMSVT2_Dust_S1(id);
        }
        
        public System.Threading.Tasks.Task<double> getCeMSVT2_Dust_S1Async(string id) {
            return base.Channel.getCeMSVT2_Dust_S1Async(id);
        }
        
        public double getCeMSVT2_Dust_S2(string id) {
            return base.Channel.getCeMSVT2_Dust_S2(id);
        }
        
        public System.Threading.Tasks.Task<double> getCeMSVT2_Dust_S2Async(string id) {
            return base.Channel.getCeMSVT2_Dust_S2Async(id);
        }
        
        public double getCeMSVT2_NO2_S1(string id) {
            return base.Channel.getCeMSVT2_NO2_S1(id);
        }
        
        public System.Threading.Tasks.Task<double> getCeMSVT2_NO2_S1Async(string id) {
            return base.Channel.getCeMSVT2_NO2_S1Async(id);
        }
        
        public double getCeMSVT2_NO2_S2(string id) {
            return base.Channel.getCeMSVT2_NO2_S2(id);
        }
        
        public System.Threading.Tasks.Task<double> getCeMSVT2_NO2_S2Async(string id) {
            return base.Channel.getCeMSVT2_NO2_S2Async(id);
        }
        
        public double getCeMSVT2_SO2_S1(string id) {
            return base.Channel.getCeMSVT2_SO2_S1(id);
        }
        
        public System.Threading.Tasks.Task<double> getCeMSVT2_SO2_S1Async(string id) {
            return base.Channel.getCeMSVT2_SO2_S1Async(id);
        }
        
        public double getCeMSVT2_SO2_S2(string id) {
            return base.Channel.getCeMSVT2_SO2_S2(id);
        }
        
        public System.Threading.Tasks.Task<double> getCeMSVT2_SO2_S2Async(string id) {
            return base.Channel.getCeMSVT2_SO2_S2Async(id);
        }
        
        public double getCeMSVT2_CO2_S1(string id) {
            return base.Channel.getCeMSVT2_CO2_S1(id);
        }
        
        public System.Threading.Tasks.Task<double> getCeMSVT2_CO2_S1Async(string id) {
            return base.Channel.getCeMSVT2_CO2_S1Async(id);
        }
        
        public double getCeMSVT2_CO2_S2(string id) {
            return base.Channel.getCeMSVT2_CO2_S2(id);
        }
        
        public System.Threading.Tasks.Task<double> getCeMSVT2_CO2_S2Async(string id) {
            return base.Channel.getCeMSVT2_CO2_S2Async(id);
        }
        
        public double getCeMSVT2_O2_S1(string id) {
            return base.Channel.getCeMSVT2_O2_S1(id);
        }
        
        public System.Threading.Tasks.Task<double> getCeMSVT2_O2_S1Async(string id) {
            return base.Channel.getCeMSVT2_O2_S1Async(id);
        }
        
        public double getCeMSVT2_O2_S2(string id) {
            return base.Channel.getCeMSVT2_O2_S2(id);
        }
        
        public System.Threading.Tasks.Task<double> getCeMSVT2_O2_S2Async(string id) {
            return base.Channel.getCeMSVT2_O2_S2Async(id);
        }
        
        public double getCeMSVT2_CO_S1(string id) {
            return base.Channel.getCeMSVT2_CO_S1(id);
        }
        
        public System.Threading.Tasks.Task<double> getCeMSVT2_CO_S1Async(string id) {
            return base.Channel.getCeMSVT2_CO_S1Async(id);
        }
        
        public double getCeMSVT2_CO_S2(string id) {
            return base.Channel.getCeMSVT2_CO_S2(id);
        }
        
        public System.Threading.Tasks.Task<double> getCeMSVT2_CO_S2Async(string id) {
            return base.Channel.getCeMSVT2_CO_S2Async(id);
        }
        
        public double getCeMSVT2_Temp_S1(string id) {
            return base.Channel.getCeMSVT2_Temp_S1(id);
        }
        
        public System.Threading.Tasks.Task<double> getCeMSVT2_Temp_S1Async(string id) {
            return base.Channel.getCeMSVT2_Temp_S1Async(id);
        }
        
        public double getCeMSVT2_Temp_S2(string id) {
            return base.Channel.getCeMSVT2_Temp_S2(id);
        }
        
        public System.Threading.Tasks.Task<double> getCeMSVT2_Temp_S2Async(string id) {
            return base.Channel.getCeMSVT2_Temp_S2Async(id);
        }
        
        public double getCongSuat_PM3_GT31(string id) {
            return base.Channel.getCongSuat_PM3_GT31(id);
        }
        
        public System.Threading.Tasks.Task<double> getCongSuat_PM3_GT31Async(string id) {
            return base.Channel.getCongSuat_PM3_GT31Async(id);
        }
        
        public double getCongSuat_PM3_GT32(string id) {
            return base.Channel.getCongSuat_PM3_GT32(id);
        }
        
        public System.Threading.Tasks.Task<double> getCongSuat_PM3_GT32Async(string id) {
            return base.Channel.getCongSuat_PM3_GT32Async(id);
        }
        
        public double getCongSuat_PM3_ST33(string id) {
            return base.Channel.getCongSuat_PM3_ST33(id);
        }
        
        public System.Threading.Tasks.Task<double> getCongSuat_PM3_ST33Async(string id) {
            return base.Channel.getCongSuat_PM3_ST33Async(id);
        }
        
        public double getCongSuat_PM22_TOTAL(string id) {
            return base.Channel.getCongSuat_PM22_TOTAL(id);
        }
        
        public System.Threading.Tasks.Task<double> getCongSuat_PM22_TOTALAsync(string id) {
            return base.Channel.getCongSuat_PM22_TOTALAsync(id);
        }
        
        public double getCongSuat_BR_GT1(string id) {
            return base.Channel.getCongSuat_BR_GT1(id);
        }
        
        public System.Threading.Tasks.Task<double> getCongSuat_BR_GT1Async(string id) {
            return base.Channel.getCongSuat_BR_GT1Async(id);
        }
        
        public double getCongSuat_BR_GT2(string id) {
            return base.Channel.getCongSuat_BR_GT2(id);
        }
        
        public System.Threading.Tasks.Task<double> getCongSuat_BR_GT2Async(string id) {
            return base.Channel.getCongSuat_BR_GT2Async(id);
        }
        
        public double getCongSuat_BR_GT3(string id) {
            return base.Channel.getCongSuat_BR_GT3(id);
        }
        
        public System.Threading.Tasks.Task<double> getCongSuat_BR_GT3Async(string id) {
            return base.Channel.getCongSuat_BR_GT3Async(id);
        }
        
        public double getCongSuat_BR_GT4(string id) {
            return base.Channel.getCongSuat_BR_GT4(id);
        }
        
        public System.Threading.Tasks.Task<double> getCongSuat_BR_GT4Async(string id) {
            return base.Channel.getCongSuat_BR_GT4Async(id);
        }
        
        public double getCongSuat_BR_GT5(string id) {
            return base.Channel.getCongSuat_BR_GT5(id);
        }
        
        public System.Threading.Tasks.Task<double> getCongSuat_BR_GT5Async(string id) {
            return base.Channel.getCongSuat_BR_GT5Async(id);
        }
        
        public double getCongSuat_BR_GT6(string id) {
            return base.Channel.getCongSuat_BR_GT6(id);
        }
        
        public System.Threading.Tasks.Task<double> getCongSuat_BR_GT6Async(string id) {
            return base.Channel.getCongSuat_BR_GT6Async(id);
        }
        
        public double getCongSuat_BR_GT7(string id) {
            return base.Channel.getCongSuat_BR_GT7(id);
        }
        
        public System.Threading.Tasks.Task<double> getCongSuat_BR_GT7Async(string id) {
            return base.Channel.getCongSuat_BR_GT7Async(id);
        }
        
        public double getCongSuat_BR_GT8(string id) {
            return base.Channel.getCongSuat_BR_GT8(id);
        }
        
        public System.Threading.Tasks.Task<double> getCongSuat_BR_GT8Async(string id) {
            return base.Channel.getCongSuat_BR_GT8Async(id);
        }
        
        public double getCongSuat_BR_ST9(string id) {
            return base.Channel.getCongSuat_BR_ST9(id);
        }
        
        public System.Threading.Tasks.Task<double> getCongSuat_BR_ST9Async(string id) {
            return base.Channel.getCongSuat_BR_ST9Async(id);
        }
        
        public double getCongSuat_BR_ST10(string id) {
            return base.Channel.getCongSuat_BR_ST10(id);
        }
        
        public System.Threading.Tasks.Task<double> getCongSuat_BR_ST10Async(string id) {
            return base.Channel.getCongSuat_BR_ST10Async(id);
        }
        
        public double getGAS_LH(string id) {
            return base.Channel.getGAS_LH(id);
        }
        
        public System.Threading.Tasks.Task<double> getGAS_LHAsync(string id) {
            return base.Channel.getGAS_LHAsync(id);
        }
        
        public double getGAS_DC(string id) {
            return base.Channel.getGAS_DC(id);
        }
        
        public System.Threading.Tasks.Task<double> getGAS_DCAsync(string id) {
            return base.Channel.getGAS_DCAsync(id);
        }
        
        public double getGAS_DC_FLOW(string id) {
            return base.Channel.getGAS_DC_FLOW(id);
        }
        
        public System.Threading.Tasks.Task<double> getGAS_DC_FLOWAsync(string id) {
            return base.Channel.getGAS_DC_FLOWAsync(id);
        }
        
        public double getCongSuat_TB1_S1(string id) {
            return base.Channel.getCongSuat_TB1_S1(id);
        }
        
        public System.Threading.Tasks.Task<double> getCongSuat_TB1_S1Async(string id) {
            return base.Channel.getCongSuat_TB1_S1Async(id);
        }
        
        public double getCongSuat_TB1_S2(string id) {
            return base.Channel.getCongSuat_TB1_S2(id);
        }
        
        public System.Threading.Tasks.Task<double> getCongSuat_TB1_S2Async(string id) {
            return base.Channel.getCongSuat_TB1_S2Async(id);
        }
        
        public string getCongSuat_TB1_NGAY(string id) {
            return base.Channel.getCongSuat_TB1_NGAY(id);
        }
        
        public System.Threading.Tasks.Task<string> getCongSuat_TB1_NGAYAsync(string id) {
            return base.Channel.getCongSuat_TB1_NGAYAsync(id);
        }
        
        public double getCongSuat_VT4_S1(string id) {
            return base.Channel.getCongSuat_VT4_S1(id);
        }
        
        public System.Threading.Tasks.Task<double> getCongSuat_VT4_S1Async(string id) {
            return base.Channel.getCongSuat_VT4_S1Async(id);
        }
        
        public double getCongSuat_VT4_S2(string id) {
            return base.Channel.getCongSuat_VT4_S2(id);
        }
        
        public System.Threading.Tasks.Task<double> getCongSuat_VT4_S2Async(string id) {
            return base.Channel.getCongSuat_VT4_S2Async(id);
        }
        
        public string getCongSuat_VT4_NGAY(string id) {
            return base.Channel.getCongSuat_VT4_NGAY(id);
        }
        
        public System.Threading.Tasks.Task<string> getCongSuat_VT4_NGAYAsync(string id) {
            return base.Channel.getCongSuat_VT4_NGAYAsync(id);
        }
    }
}
