//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_API.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/WebServiceGIS.asmx", ConfigurationName="ServiceReference1.WebServiceGISSoap")]
    public interface WebServiceGISSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_PM1_GT11", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCongSuat_PM1_GT11(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_PM1_GT11", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCongSuat_PM1_GT11Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_PM1_GT12", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCongSuat_PM1_GT12(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_PM1_GT12", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCongSuat_PM1_GT12Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_PM1_GT13", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCongSuat_PM1_GT13(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_PM1_GT13", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCongSuat_PM1_GT13Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_PM1_ST14", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCongSuat_PM1_ST14(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_PM1_ST14", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCongSuat_PM1_ST14Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_PM4_GT41", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCongSuat_PM4_GT41(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_PM4_GT41", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCongSuat_PM4_GT41Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_PM4_GT42", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCongSuat_PM4_GT42(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_PM4_GT42", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCongSuat_PM4_GT42Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_PM4_ST43", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCongSuat_PM4_ST43(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_PM4_ST43", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCongSuat_PM4_ST43Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_PM21_GT21", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCongSuat_PM21_GT21(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_PM21_GT21", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCongSuat_PM21_GT21Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_PM21_GT22", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCongSuat_PM21_GT22(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_PM21_GT22", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCongSuat_PM21_GT22Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_PM21_ST23", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCongSuat_PM21_ST23(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_PM21_ST23", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCongSuat_PM21_ST23Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_PM21MR_GT24", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCongSuat_PM21MR_GT24(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_PM21MR_GT24", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCongSuat_PM21MR_GT24Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_PM21MR_GT25", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCongSuat_PM21MR_GT25(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_PM21MR_GT25", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCongSuat_PM21MR_GT25Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_PM21MR_ST26", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCongSuat_PM21MR_ST26(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_PM21MR_ST26", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCongSuat_PM21MR_ST26Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_VT2_S1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCongSuat_VT2_S1(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_VT2_S1", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCongSuat_VT2_S1Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_VT2_S2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCongSuat_VT2_S2(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_VT2_S2", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCongSuat_VT2_S2Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_MD1_S1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCongSuat_MD1_S1(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_MD1_S1", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCongSuat_MD1_S1Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_MD1_S2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCongSuat_MD1_S2(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_MD1_S2", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCongSuat_MD1_S2Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_BTS_H1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCongSuat_BTS_H1(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_BTS_H1", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCongSuat_BTS_H1Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_BTS_H2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCongSuat_BTS_H2(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_BTS_H2", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCongSuat_BTS_H2Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_BK_H1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCongSuat_BK_H1(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_BK_H1", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCongSuat_BK_H1Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_BK_H2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCongSuat_BK_H2(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_BK_H2", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCongSuat_BK_H2Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_SP3_H1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCongSuat_SP3_H1(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_SP3_H1", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCongSuat_SP3_H1Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_SP3_H2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCongSuat_SP3_H2(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCongSuat_SP3_H2", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCongSuat_SP3_H2Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCeMSVT2_Dust_S1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCeMSVT2_Dust_S1(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCeMSVT2_Dust_S1", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCeMSVT2_Dust_S1Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCeMSVT2_Dust_S2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCeMSVT2_Dust_S2(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCeMSVT2_Dust_S2", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCeMSVT2_Dust_S2Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCeMSVT2_NO2_S1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCeMSVT2_NO2_S1(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCeMSVT2_NO2_S1", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCeMSVT2_NO2_S1Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCeMSVT2_NO2_S2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCeMSVT2_NO2_S2(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCeMSVT2_NO2_S2", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCeMSVT2_NO2_S2Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCeMSVT2_SO2_S1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCeMSVT2_SO2_S1(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCeMSVT2_SO2_S1", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCeMSVT2_SO2_S1Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCeMSVT2_SO2_S2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCeMSVT2_SO2_S2(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCeMSVT2_SO2_S2", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCeMSVT2_SO2_S2Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCeMSVT2_CO2_S1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCeMSVT2_CO2_S1(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCeMSVT2_CO2_S1", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCeMSVT2_CO2_S1Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCeMSVT2_CO2_S2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCeMSVT2_CO2_S2(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCeMSVT2_CO2_S2", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCeMSVT2_CO2_S2Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCeMSVT2_O2_S1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCeMSVT2_O2_S1(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCeMSVT2_O2_S1", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCeMSVT2_O2_S1Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCeMSVT2_O2_S2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCeMSVT2_O2_S2(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCeMSVT2_O2_S2", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCeMSVT2_O2_S2Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCeMSVT2_CO_S1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCeMSVT2_CO_S1(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCeMSVT2_CO_S1", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCeMSVT2_CO_S1Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCeMSVT2_CO_S2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCeMSVT2_CO_S2(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCeMSVT2_CO_S2", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCeMSVT2_CO_S2Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCeMSVT2_Temp_S1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCeMSVT2_Temp_S1(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCeMSVT2_Temp_S1", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCeMSVT2_Temp_S1Async(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCeMSVT2_Temp_S2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double getCeMSVT2_Temp_S2(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/WebServiceGIS.asmx/getCeMSVT2_Temp_S2", ReplyAction="*")]
        System.Threading.Tasks.Task<double> getCeMSVT2_Temp_S2Async(string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceGISSoapChannel : WEB_API.ServiceReference1.WebServiceGISSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceGISSoapClient : System.ServiceModel.ClientBase<WEB_API.ServiceReference1.WebServiceGISSoap>, WEB_API.ServiceReference1.WebServiceGISSoap {
        
        public WebServiceGISSoapClient() {
        }
        
        public WebServiceGISSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceGISSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceGISSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceGISSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double getCongSuat_PM1_GT11(string id) {
            return base.Channel.getCongSuat_PM1_GT11(id);
        }
        
        public System.Threading.Tasks.Task<double> getCongSuat_PM1_GT11Async(string id) {
            return base.Channel.getCongSuat_PM1_GT11Async(id);
        }
        
        public double getCongSuat_PM1_GT12(string id) {
            return base.Channel.getCongSuat_PM1_GT12(id);
        }
        
        public System.Threading.Tasks.Task<double> getCongSuat_PM1_GT12Async(string id) {
            return base.Channel.getCongSuat_PM1_GT12Async(id);
        }
        
        public double getCongSuat_PM1_GT13(string id) {
            return base.Channel.getCongSuat_PM1_GT13(id);
        }
        
        public System.Threading.Tasks.Task<double> getCongSuat_PM1_GT13Async(string id) {
            return base.Channel.getCongSuat_PM1_GT13Async(id);
        }
        
        public double getCongSuat_PM1_ST14(string id) {
            return base.Channel.getCongSuat_PM1_ST14(id);
        }
        
        public System.Threading.Tasks.Task<double> getCongSuat_PM1_ST14Async(string id) {
            return base.Channel.getCongSuat_PM1_ST14Async(id);
        }
        
        public double getCongSuat_PM4_GT41(string id) {
            return base.Channel.getCongSuat_PM4_GT41(id);
        }
        
        public System.Threading.Tasks.Task<double> getCongSuat_PM4_GT41Async(string id) {
            return base.Channel.getCongSuat_PM4_GT41Async(id);
        }
        
        public double getCongSuat_PM4_GT42(string id) {
            return base.Channel.getCongSuat_PM4_GT42(id);
        }
        
        public System.Threading.Tasks.Task<double> getCongSuat_PM4_GT42Async(string id) {
            return base.Channel.getCongSuat_PM4_GT42Async(id);
        }
        
        public double getCongSuat_PM4_ST43(string id) {
            return base.Channel.getCongSuat_PM4_ST43(id);
        }
        
        public System.Threading.Tasks.Task<double> getCongSuat_PM4_ST43Async(string id) {
            return base.Channel.getCongSuat_PM4_ST43Async(id);
        }
        
        public double getCongSuat_PM21_GT21(string id) {
            return base.Channel.getCongSuat_PM21_GT21(id);
        }
        
        public System.Threading.Tasks.Task<double> getCongSuat_PM21_GT21Async(string id) {
            return base.Channel.getCongSuat_PM21_GT21Async(id);
        }
        
        public double getCongSuat_PM21_GT22(string id) {
            return base.Channel.getCongSuat_PM21_GT22(id);
        }
        
        public System.Threading.Tasks.Task<double> getCongSuat_PM21_GT22Async(string id) {
            return base.Channel.getCongSuat_PM21_GT22Async(id);
        }
        
        public double getCongSuat_PM21_ST23(string id) {
            return base.Channel.getCongSuat_PM21_ST23(id);
        }
        
        public System.Threading.Tasks.Task<double> getCongSuat_PM21_ST23Async(string id) {
            return base.Channel.getCongSuat_PM21_ST23Async(id);
        }
        
        public double getCongSuat_PM21MR_GT24(string id) {
            return base.Channel.getCongSuat_PM21MR_GT24(id);
        }
        
        public System.Threading.Tasks.Task<double> getCongSuat_PM21MR_GT24Async(string id) {
            return base.Channel.getCongSuat_PM21MR_GT24Async(id);
        }
        
        public double getCongSuat_PM21MR_GT25(string id) {
            return base.Channel.getCongSuat_PM21MR_GT25(id);
        }
        
        public System.Threading.Tasks.Task<double> getCongSuat_PM21MR_GT25Async(string id) {
            return base.Channel.getCongSuat_PM21MR_GT25Async(id);
        }
        
        public double getCongSuat_PM21MR_ST26(string id) {
            return base.Channel.getCongSuat_PM21MR_ST26(id);
        }
        
        public System.Threading.Tasks.Task<double> getCongSuat_PM21MR_ST26Async(string id) {
            return base.Channel.getCongSuat_PM21MR_ST26Async(id);
        }
        
        public double getCongSuat_VT2_S1(string id) {
            return base.Channel.getCongSuat_VT2_S1(id);
        }
        
        public System.Threading.Tasks.Task<double> getCongSuat_VT2_S1Async(string id) {
            return base.Channel.getCongSuat_VT2_S1Async(id);
        }
        
        public double getCongSuat_VT2_S2(string id) {
            return base.Channel.getCongSuat_VT2_S2(id);
        }
        
        public System.Threading.Tasks.Task<double> getCongSuat_VT2_S2Async(string id) {
            return base.Channel.getCongSuat_VT2_S2Async(id);
        }
        
        public double getCongSuat_MD1_S1(string id) {
            return base.Channel.getCongSuat_MD1_S1(id);
        }
        
        public System.Threading.Tasks.Task<double> getCongSuat_MD1_S1Async(string id) {
            return base.Channel.getCongSuat_MD1_S1Async(id);
        }
        
        public double getCongSuat_MD1_S2(string id) {
            return base.Channel.getCongSuat_MD1_S2(id);
        }
        
        public System.Threading.Tasks.Task<double> getCongSuat_MD1_S2Async(string id) {
            return base.Channel.getCongSuat_MD1_S2Async(id);
        }
        
        public double getCongSuat_BTS_H1(string id) {
            return base.Channel.getCongSuat_BTS_H1(id);
        }
        
        public System.Threading.Tasks.Task<double> getCongSuat_BTS_H1Async(string id) {
            return base.Channel.getCongSuat_BTS_H1Async(id);
        }
        
        public double getCongSuat_BTS_H2(string id) {
            return base.Channel.getCongSuat_BTS_H2(id);
        }
        
        public System.Threading.Tasks.Task<double> getCongSuat_BTS_H2Async(string id) {
            return base.Channel.getCongSuat_BTS_H2Async(id);
        }
        
        public double getCongSuat_BK_H1(string id) {
            return base.Channel.getCongSuat_BK_H1(id);
        }
        
        public System.Threading.Tasks.Task<double> getCongSuat_BK_H1Async(string id) {
            return base.Channel.getCongSuat_BK_H1Async(id);
        }
        
        public double getCongSuat_BK_H2(string id) {
            return base.Channel.getCongSuat_BK_H2(id);
        }
        
        public System.Threading.Tasks.Task<double> getCongSuat_BK_H2Async(string id) {
            return base.Channel.getCongSuat_BK_H2Async(id);
        }
        
        public double getCongSuat_SP3_H1(string id) {
            return base.Channel.getCongSuat_SP3_H1(id);
        }
        
        public System.Threading.Tasks.Task<double> getCongSuat_SP3_H1Async(string id) {
            return base.Channel.getCongSuat_SP3_H1Async(id);
        }
        
        public double getCongSuat_SP3_H2(string id) {
            return base.Channel.getCongSuat_SP3_H2(id);
        }
        
        public System.Threading.Tasks.Task<double> getCongSuat_SP3_H2Async(string id) {
            return base.Channel.getCongSuat_SP3_H2Async(id);
        }
        
        public double getCeMSVT2_Dust_S1(string id) {
            return base.Channel.getCeMSVT2_Dust_S1(id);
        }
        
        public System.Threading.Tasks.Task<double> getCeMSVT2_Dust_S1Async(string id) {
            return base.Channel.getCeMSVT2_Dust_S1Async(id);
        }
        
        public double getCeMSVT2_Dust_S2(string id) {
            return base.Channel.getCeMSVT2_Dust_S2(id);
        }
        
        public System.Threading.Tasks.Task<double> getCeMSVT2_Dust_S2Async(string id) {
            return base.Channel.getCeMSVT2_Dust_S2Async(id);
        }
        
        public double getCeMSVT2_NO2_S1(string id) {
            return base.Channel.getCeMSVT2_NO2_S1(id);
        }
        
        public System.Threading.Tasks.Task<double> getCeMSVT2_NO2_S1Async(string id) {
            return base.Channel.getCeMSVT2_NO2_S1Async(id);
        }
        
        public double getCeMSVT2_NO2_S2(string id) {
            return base.Channel.getCeMSVT2_NO2_S2(id);
        }
        
        public System.Threading.Tasks.Task<double> getCeMSVT2_NO2_S2Async(string id) {
            return base.Channel.getCeMSVT2_NO2_S2Async(id);
        }
        
        public double getCeMSVT2_SO2_S1(string id) {
            return base.Channel.getCeMSVT2_SO2_S1(id);
        }
        
        public System.Threading.Tasks.Task<double> getCeMSVT2_SO2_S1Async(string id) {
            return base.Channel.getCeMSVT2_SO2_S1Async(id);
        }
        
        public double getCeMSVT2_SO2_S2(string id) {
            return base.Channel.getCeMSVT2_SO2_S2(id);
        }
        
        public System.Threading.Tasks.Task<double> getCeMSVT2_SO2_S2Async(string id) {
            return base.Channel.getCeMSVT2_SO2_S2Async(id);
        }
        
        public double getCeMSVT2_CO2_S1(string id) {
            return base.Channel.getCeMSVT2_CO2_S1(id);
        }
        
        public System.Threading.Tasks.Task<double> getCeMSVT2_CO2_S1Async(string id) {
            return base.Channel.getCeMSVT2_CO2_S1Async(id);
        }
        
        public double getCeMSVT2_CO2_S2(string id) {
            return base.Channel.getCeMSVT2_CO2_S2(id);
        }
        
        public System.Threading.Tasks.Task<double> getCeMSVT2_CO2_S2Async(string id) {
            return base.Channel.getCeMSVT2_CO2_S2Async(id);
        }
        
        public double getCeMSVT2_O2_S1(string id) {
            return base.Channel.getCeMSVT2_O2_S1(id);
        }
        
        public System.Threading.Tasks.Task<double> getCeMSVT2_O2_S1Async(string id) {
            return base.Channel.getCeMSVT2_O2_S1Async(id);
        }
        
        public double getCeMSVT2_O2_S2(string id) {
            return base.Channel.getCeMSVT2_O2_S2(id);
        }
        
        public System.Threading.Tasks.Task<double> getCeMSVT2_O2_S2Async(string id) {
            return base.Channel.getCeMSVT2_O2_S2Async(id);
        }
        
        public double getCeMSVT2_CO_S1(string id) {
            return base.Channel.getCeMSVT2_CO_S1(id);
        }
        
        public System.Threading.Tasks.Task<double> getCeMSVT2_CO_S1Async(string id) {
            return base.Channel.getCeMSVT2_CO_S1Async(id);
        }
        
        public double getCeMSVT2_CO_S2(string id) {
            return base.Channel.getCeMSVT2_CO_S2(id);
        }
        
        public System.Threading.Tasks.Task<double> getCeMSVT2_CO_S2Async(string id) {
            return base.Channel.getCeMSVT2_CO_S2Async(id);
        }
        
        public double getCeMSVT2_Temp_S1(string id) {
            return base.Channel.getCeMSVT2_Temp_S1(id);
        }
        
        public System.Threading.Tasks.Task<double> getCeMSVT2_Temp_S1Async(string id) {
            return base.Channel.getCeMSVT2_Temp_S1Async(id);
        }
        
        public double getCeMSVT2_Temp_S2(string id) {
            return base.Channel.getCeMSVT2_Temp_S2(id);
        }
        
        public System.Threading.Tasks.Task<double> getCeMSVT2_Temp_S2Async(string id) {
            return base.Channel.getCeMSVT2_Temp_S2Async(id);
        }
    }
}
